exports.cssSnippets = [
  { label: "a-c-p", insertText: "a-c-p", detail: "鼠标手型", style: "cursor: pointer", explain: "" },
  { label: "a-fx", insertText: "a-fx", detail: "弹性布局，垂直居中", style: "display: flex;align-items: center", explain: "" },
  { label: "a-jc-c", insertText: "a-jc-c", detail: "主轴居中", style: "justify-content: center", explain: "" },
  { label: "a-jc-sb", insertText: "a-jc-sb", detail: "主轴两端对齐", style: "justify-content: space-between", explain: "" },
  { label: "a-d-f", insertText: "a-d-f", detail: "flex 布局", style: "display: flex", explain: "" },
  { label: "a-d-c", insertText: "a-d-c", detail: "将容器消失，仅保留子元素布局", style: "display: contents", explain: "" },
  { label: "a-jc-fe", insertText: "a-jc-fe", detail: "主轴靠右对齐", style: "justify-content: flex-end", explain: "" },
  { label: "a-ai-c", insertText: "a-ai-c", detail: "交叉轴居中", style: "align-items: center", explain: "" },
  { label: "a-fd-c", insertText: "a-fd-c", detail: "垂直方向排列", style: "flex-direction: column", explain: "" },
  { label: "a-p-r", insertText: "a-p-r", detail: "相对定位", style: "position: relative", explain: "" },
  { label: "a-p-a", insertText: "a-p-a", detail: "绝对定位", style: "position: absolute", explain: "" },
  { label: "a-d-n", insertText: "a-d-n", detail: "隐藏元素", style: "display: none !important", explain: "" },
  { label: "a-inset", insertText: "a-inset", detail: "上下左右 0", style: "top: 0;left: 0;right: 0;bottom: 0", explain: "" },
  { label: "a-pe-n", insertText: "a-pe-n", detail: "禁止鼠标事件", style: "pointer-events: none", explain: "" },
  { label: "a-o-h", insertText: "a-o-h", detail: "隐藏溢出", style: "overflow: hidden", explain: "" },
  { label: "a-o-a", insertText: "a-o-a", detail: "自动溢出", style: "overflow: auto", explain: "" },
  { label: "a-o-ha", insertText: "a-o-ha", detail: "上下隐藏，左右自动", style: "overflow: hidden auto", explain: "" },
  { label: "a-ellipsis", insertText: "a-ellipsis", detail: "文本溢出省略号", style: "overflow: hidden;white-space: nowrap;text-overflow: ellipsis", explain: "" },
  { label: "a-w-100", insertText: "a-w-100", detail: "宽度 100%", style: "width: 100% !important", explain: "" },
  { label: "a-mh-100", insertText: "a-mh-100", detail: "最小高度 100%", style: "min-height: 100%", explain: "" },
  { label: "a-h-100", insertText: "a-h-100", detail: "高度 100%", style: "height: 100%", explain: "" },
  { label: "a-mw-0", insertText: "a-mw-0", detail: "最小宽度 0", style: "min-width: 0", explain: "" },
  { label: "a-mh-0", insertText: "a-mh-0", detail: "最小高度 0", style: "min-height: 0", explain: "" },
  { label: "a-fs-0", insertText: "a-fs-0", detail: "禁止缩小", style: "flex-shrink: 0", explain: "" },
  { label: "a-h-0", insertText: "a-h-0", detail: "高度 0", style: "height: 0", explain: "" },
  { label: "a-f-1", insertText: "a-f-1", detail: "弹性伸展 1", style: "flex: 1", explain: "" },
  { label: "a-f-u", insertText: "a-f-u", detail: "取消该元素的放大比例", style: "flex-grow: unset !important", explain: "" },
  { label: "a-o-0", insertText: "a-o-0", detail: "透明度 0", style: "opacity: 0", explain: "" },
  { label: "a-o-1", insertText: "a-o-1", detail: "透明度 1", style: "opacity: 1", explain: "" }
];
